spring:
  application:
    name: workflow
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    redis:
      host: localhost
      port: 6379
    kafka:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/workflowdb
    username: workflow
    password: workflow
  jpa:
    hibernate:
      ddl-auto: update