spring:
  application:
    name: workflow
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: non-null
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgres:5432/workflowdb
    username: workflow
    password: workflow
  jpa:
    hibernate:
      ddl-auto: update