spring:
  application:
    name: workflow
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    redis:
      host: localhost
      port: 6379
    kafka:
      bootstrap-servers: localhost:9092